// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan_SE104.Model;

#nullable disable

namespace QuanLyKhachSan_SE104.Migrations
{
    [DbContext(typeof(QuanLyKhachSanContext))]
    [Migration("20260515120439_AddLichSuCocTable")]
    partial class AddLichSuCocTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.ChiTietDatPhong", b =>
                {
                    b.Property<int>("MaChiTietDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChiTietDatPhong"));

                    b.Property<decimal>("GiaDat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCheckIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayCheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDatPhong");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiTietDatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaChiTietDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChiTietDV"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaChiTietDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianSuDung")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaChiTietDV");

                    b.HasIndex("MaChiTietDatPhong");

                    b.HasIndex("MaDichVu");

                    b.ToTable("ChiTietDichVus");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDatPhong"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TrangThaiCoc")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiDat")
                        .HasColumnType("int");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LoaiDichVu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PhuPhi")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("int");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongTienDichVu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongTienPhong")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDatPhong")
                        .IsUnique();

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("CCCD_Passport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.LichSuCoc", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LoaiGiaoDich")
                        .HasColumnType("int");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int?>("MaDatPhongMoi")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaDatPhongMoi");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichSuCocs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<decimal>("GiaMacDinh")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PhuPhiThemGio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SoGiuong")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<bool>("ChucVu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TrangThaiLamViec")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int>("SoTang")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiThue");

                    b.Property<int>("TrangThaiDonDep")
                        .HasColumnType("int");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.ChiTietDatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan_SE104.Model.DatPhong", "DatPhong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_SE104.Model.Phong", "Phong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.ChiTietDichVu", b =>
                {
                    b.HasOne("QuanLyKhachSan_SE104.Model.ChiTietDatPhong", "ChiTietDatPhong")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaChiTietDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_SE104.Model.DichVu", "DichVu")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.DatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan_SE104.Model.KhachHang", "KhachHang")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_SE104.Model.NhanVien", "NhanVien")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.HoaDon", b =>
                {
                    b.HasOne("QuanLyKhachSan_SE104.Model.DatPhong", "DatPhong")
                        .WithOne("HoaDon")
                        .HasForeignKey("QuanLyKhachSan_SE104.Model.HoaDon", "MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_SE104.Model.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.LichSuCoc", b =>
                {
                    b.HasOne("QuanLyKhachSan_SE104.Model.DatPhong", "DatPhong")
                        .WithMany("LichSuCocs")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_SE104.Model.DatPhong", null)
                        .WithMany()
                        .HasForeignKey("MaDatPhongMoi");

                    b.HasOne("QuanLyKhachSan_SE104.Model.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.Phong", b =>
                {
                    b.HasOne("QuanLyKhachSan_SE104.Model.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKhachSan_SE104.Model.NhanVien", "NhanVien")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.ChiTietDatPhong", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.DatPhong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");

                    b.Navigation("HoaDon")
                        .IsRequired();

                    b.Navigation("LichSuCocs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.NhanVien", b =>
                {
                    b.Navigation("DatPhongs");

                    b.Navigation("HoaDons");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKhachSan_SE104.Model.Phong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
